/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Account_slugRouteImport } from './routes/$account_slug'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DevRouteImport } from './routes/dev'
import { Route as SignRouteImport } from './routes/sign'
import { Route as Account_slugIndexRouteImport } from './routes/$account_slug/index'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminStatsRouteImport } from './routes/admin/stats'
import { Route as DevLettersRouteImport } from './routes/dev/letters'
import { Route as SignIndexRouteImport } from './routes/sign/index'
import { Route as SignVerifyRouteImport } from './routes/sign/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Account_slugRoute = Account_slugRouteImport.update({
  id: '/$account_slug',
  path: '/$account_slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const Account_slugIndexRoute = Account_slugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Account_slugRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRoute,
} as any)
const DevLettersRoute = DevLettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => DevRoute,
} as any)
const SignIndexRoute = SignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignRoute,
} as any)
const SignVerifyRoute = SignVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => SignRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$account_slug': typeof Account_slugRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/sign': typeof SignRouteWithChildren
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/dev/letters': typeof DevLettersRoute
  '/sign/verify': typeof SignVerifyRoute
  '/$account_slug/': typeof Account_slugIndexRoute
  '/sign/': typeof SignIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/dev/letters': typeof DevLettersRoute
  '/sign/verify': typeof SignVerifyRoute
  '/$account_slug': typeof Account_slugIndexRoute
  '/sign': typeof SignIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$account_slug': typeof Account_slugRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/sign': typeof SignRouteWithChildren
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/dev/letters': typeof DevLettersRoute
  '/sign/verify': typeof SignVerifyRoute
  '/$account_slug/': typeof Account_slugIndexRoute
  '/sign/': typeof SignIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$account_slug'
    | '/accounts'
    | '/admin'
    | '/dev'
    | '/sign'
    | '/admin/jobs'
    | '/admin/stats'
    | '/dev/letters'
    | '/sign/verify'
    | '/$account_slug/'
    | '/sign/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/admin'
    | '/dev'
    | '/admin/jobs'
    | '/admin/stats'
    | '/dev/letters'
    | '/sign/verify'
    | '/$account_slug'
    | '/sign'
  id:
    | '__root__'
    | '/'
    | '/$account_slug'
    | '/accounts'
    | '/admin'
    | '/dev'
    | '/sign'
    | '/admin/jobs'
    | '/admin/stats'
    | '/dev/letters'
    | '/sign/verify'
    | '/$account_slug/'
    | '/sign/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Account_slugRoute: typeof Account_slugRouteWithChildren
  AccountsRoute: typeof AccountsRoute
  AdminRoute: typeof AdminRouteWithChildren
  DevRoute: typeof DevRouteWithChildren
  SignRoute: typeof SignRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$account_slug': {
      id: '/$account_slug'
      path: '/$account_slug'
      fullPath: '/$account_slug'
      preLoaderRoute: typeof Account_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$account_slug/': {
      id: '/$account_slug/'
      path: '/'
      fullPath: '/$account_slug/'
      preLoaderRoute: typeof Account_slugIndexRouteImport
      parentRoute: typeof Account_slugRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dev/letters': {
      id: '/dev/letters'
      path: '/letters'
      fullPath: '/dev/letters'
      preLoaderRoute: typeof DevLettersRouteImport
      parentRoute: typeof DevRoute
    }
    '/sign/': {
      id: '/sign/'
      path: '/'
      fullPath: '/sign/'
      preLoaderRoute: typeof SignIndexRouteImport
      parentRoute: typeof SignRoute
    }
    '/sign/verify': {
      id: '/sign/verify'
      path: '/verify'
      fullPath: '/sign/verify'
      preLoaderRoute: typeof SignVerifyRouteImport
      parentRoute: typeof SignRoute
    }
  }
}

interface Account_slugRouteChildren {
  Account_slugIndexRoute: typeof Account_slugIndexRoute
}

const Account_slugRouteChildren: Account_slugRouteChildren = {
  Account_slugIndexRoute: Account_slugIndexRoute,
}

const Account_slugRouteWithChildren = Account_slugRoute._addFileChildren(
  Account_slugRouteChildren,
)

interface AdminRouteChildren {
  AdminJobsRoute: typeof AdminJobsRoute
  AdminStatsRoute: typeof AdminStatsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminJobsRoute: AdminJobsRoute,
  AdminStatsRoute: AdminStatsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DevRouteChildren {
  DevLettersRoute: typeof DevLettersRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevLettersRoute: DevLettersRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

interface SignRouteChildren {
  SignVerifyRoute: typeof SignVerifyRoute
  SignIndexRoute: typeof SignIndexRoute
}

const SignRouteChildren: SignRouteChildren = {
  SignVerifyRoute: SignVerifyRoute,
  SignIndexRoute: SignIndexRoute,
}

const SignRouteWithChildren = SignRoute._addFileChildren(SignRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Account_slugRoute: Account_slugRouteWithChildren,
  AccountsRoute: AccountsRoute,
  AdminRoute: AdminRouteWithChildren,
  DevRoute: DevRouteWithChildren,
  SignRoute: SignRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
