/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as SignRouteImport } from './routes/sign'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as SlugJobsRouteImport } from './routes/$slug/jobs'
import { Route as SlugStatsRouteImport } from './routes/$slug/stats'
import { Route as SignIndexRouteImport } from './routes/sign/index'
import { Route as SignVerifyRouteImport } from './routes/sign/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const SlugJobsRoute = SlugJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => SlugRoute,
} as any)
const SlugStatsRoute = SlugStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => SlugRoute,
} as any)
const SignIndexRoute = SignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignRoute,
} as any)
const SignVerifyRoute = SignVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => SignRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/sign': typeof SignRouteWithChildren
  '/$slug/jobs': typeof SlugJobsRoute
  '/$slug/stats': typeof SlugStatsRoute
  '/sign/verify': typeof SignVerifyRoute
  '/$slug/': typeof SlugIndexRoute
  '/sign/': typeof SignIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug/jobs': typeof SlugJobsRoute
  '/$slug/stats': typeof SlugStatsRoute
  '/sign/verify': typeof SignVerifyRoute
  '/$slug': typeof SlugIndexRoute
  '/sign': typeof SignIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/sign': typeof SignRouteWithChildren
  '/$slug/jobs': typeof SlugJobsRoute
  '/$slug/stats': typeof SlugStatsRoute
  '/sign/verify': typeof SignVerifyRoute
  '/$slug/': typeof SlugIndexRoute
  '/sign/': typeof SignIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/sign'
    | '/$slug/jobs'
    | '/$slug/stats'
    | '/sign/verify'
    | '/$slug/'
    | '/sign/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$slug/jobs' | '/$slug/stats' | '/sign/verify' | '/$slug' | '/sign'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/sign'
    | '/$slug/jobs'
    | '/$slug/stats'
    | '/sign/verify'
    | '/$slug/'
    | '/sign/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  SignRoute: typeof SignRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/jobs': {
      id: '/$slug/jobs'
      path: '/jobs'
      fullPath: '/$slug/jobs'
      preLoaderRoute: typeof SlugJobsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/stats': {
      id: '/$slug/stats'
      path: '/stats'
      fullPath: '/$slug/stats'
      preLoaderRoute: typeof SlugStatsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/sign/': {
      id: '/sign/'
      path: '/'
      fullPath: '/sign/'
      preLoaderRoute: typeof SignIndexRouteImport
      parentRoute: typeof SignRoute
    }
    '/sign/verify': {
      id: '/sign/verify'
      path: '/verify'
      fullPath: '/sign/verify'
      preLoaderRoute: typeof SignVerifyRouteImport
      parentRoute: typeof SignRoute
    }
  }
}

interface SlugRouteChildren {
  SlugJobsRoute: typeof SlugJobsRoute
  SlugStatsRoute: typeof SlugStatsRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugJobsRoute: SlugJobsRoute,
  SlugStatsRoute: SlugStatsRoute,
  SlugIndexRoute: SlugIndexRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

interface SignRouteChildren {
  SignVerifyRoute: typeof SignVerifyRoute
  SignIndexRoute: typeof SignIndexRoute
}

const SignRouteChildren: SignRouteChildren = {
  SignVerifyRoute: SignVerifyRoute,
  SignIndexRoute: SignIndexRoute,
}

const SignRouteWithChildren = SignRoute._addFileChildren(SignRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  SignRoute: SignRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
