// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import AutoSubmitController from "controllers/auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import ElementRemovalController from "controllers/element_removal_controller"
application.register("element-removal", ElementRemovalController)

import CopyToClipboardController from "controllers/copy_to_clipboard_controller"
application.register("copy-to-clipboard", CopyToClipboardController)

import ButtonLoadingController from "controllers/button_loading_controller"
application.register("button-loading", ButtonLoadingController)

import ThemeController from "controllers/theme_controller"
application.register("theme", ThemeController)
